In [1]:
import numpy as np

# Create a 1D numpy array
arr = np.array([1, 2, 3, 4, 5])
print("1D array:", arr)

# Create a 2D numpy array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", matrix)

# Array arithmetic
sum_arr = arr + 10
print("Add 10 to each element:", sum_arr)

# Element-wise multiplication
mult_arr = arr * 2
print("Multiply each element by 2:", mult_arr)

# Basic statistics
print("Mean:", arr.mean())
print("Sum:", arr.sum())
print("Max:", arr.max())

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Add 10 to each element: [11 12 13 14 15]
Multiply each element by 2: [ 2  4  6  8 10]
Mean: 3.0
Sum: 15
Max: 5


In [2]:
# Square each element in arr
squared_arr = arr ** 2
print("Squared array:", squared_arr)

# Transpose the matrix
transposed_matrix = matrix.T
print("Transposed matrix:\n", transposed_matrix)

# Dot product of arr with itself
dot_product = np.dot(arr, arr)
print("Dot product of arr with itself:", dot_product)

# Sum along columns of matrix
col_sum = matrix.sum(axis=0)
print("Column-wise sum of matrix:", col_sum)

Squared array: [ 1  4  9 16 25]
Transposed matrix:
 [[1 4]
 [2 5]
 [3 6]]
Dot product of arr with itself: 55
Column-wise sum of matrix: [5 7 9]


In [ ]:
# %pip install scikit-learn

from sklearn.linear_model import LinearRegression

# Use arr as features (reshaped to 2D) and squared_arr as target for a simple regression
X = arr.reshape(-1, 1)
y = squared_arr

model = LinearRegression()
model.fit(X, y)

# Predict using the trained model
predictions = model.predict(X)
print("Predictions:", predictions)
print("Actual:", y)

   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/10.7 MB 730.2 kB/s eta 0:00:14
   - -------------------------------------- 0.5/10.7 MB 730.2 kB/s eta 0:00:14
   -- ------------------------------------- 0.8/10.7 MB 799.2 kB/s eta 0:00:13
   --- ------------------------------------ 1.0/10.7 MB 853.0 kB/s eta 0:00:12
   ---- ----------------------------------- 1.3/10.7 MB 907.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.6/10.7 MB 932.2 kB/s eta 0:00:10
   ------ --------------------------------- 1.8/10.7 MB 949.8 kB/s eta 0:00:10
   ------- ----------------


[notice] A new release of pip is available: 25.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


Predictions: [-1.  5. 11. 17. 23.]
Actual: [ 1  4  9 16 25]
